### ISSUE TITLE
Passing extra command line to go get

### ISSUE THREAD

**Issue by fzerorubigd** [constabulary/gb-vendor#1]
I want to write another plugin and I use this one as base for that plugin, but there is a problem for passing extra parameter to actual tool (in my case, godoc, and in this one go get) 
for example I want to pass -v to go get (just for demonstration) : 

```
gb vendor -v github.com/constabulary/gb-vendor
2015/05/11 15:16:16 INFO project root "/home/f0rud/workspace/middleware"
flag provided but not defined: -v
Usage of /home/f0rud/gospace/bin/gb-vendor:
  -p string
        project directory (default "/home/f0rud/workspace/middleware")
2015/05/11 15:16:16 command "vendor" failed: exit status 2

```

**Comment by davecheney** [comment]
gb vendor has been rewritten.
