### ISSUE TITLE
Vendor specific version of a package

### ISSUE THREAD

**Issue by davidkaya** [constabulary/gb-vendor#4]
I was thinking that it would be nice if gb-vendor had additional arguments, where user would be able to specify commit/branch of a package he or she wants to vendor.

Something like `gb-vendor -c 21dc14a51f github.com/user/sample` or `gb-vendor -b branch_name github.com/user/sample`

If you think it is a good idea, I could provide PR as soon as I finish implementing it.

**Comment by davecheney** [comment]
At the moment gb vendor I'd a crappy wrapper around go get, which is a
crappy wrapper around git clone.

In the near (less than a month) I'll start work on a new gb vendor that
doesn't wrap any of these tools, but for the moment my advice to people who
need that level of control is to skip the wrappers and just use git
directly.

**Comment by davidkaya** [comment]
@davecheney 
I have created own plugin with support for branches, commits and .git folder deleting (all optional): https://github.com/davidkaya/gb-vendor/tree/package_versions

I can create a PR if you want.

**Comment by davidkaya** [comment]
@davecheney 
I have created fork with support for branches, commits and .git folder deleting (all optional through flags): https://github.com/davidkaya/gb-vendor/tree/package_versions
If you are interested I can create a PR.

**Comment by davidkaya** [comment]
@davecheney 
I have created a fork which supports branches, commits and .git folder deleting (all optional) and it does not use `go get` but only git: https://github.com/davidkaya/gb-vendor/tree/package_versions
I can create PR if you want.

**Comment by davidkaya** [comment]
@davecheney 
If you are interested I can help you with gb-vendor. All I need is your expectations from what the new gb-vendor should be capable of doing. By the time you start working on the gb-vendor I may have working prototype ready and if you will be interested, you can use that or if you won't like it you can start working on your own implementation as you would now. I see `gb` as a very perspective project so I will be happy to help.
