### ISSUE TITLE
Branch pinning comments

### ISSUE THREAD

**Issue by andrewchambers** [constabulary/gb-vendor#6]
I think the gb vendor plugin could potentially follow branch pinning comments.

import "foo.com/bar/baz" // branch/stable/1.x

The command gb vendor would ensure all packages in the project have the same pinned branch. Combined with this simple feature, I think gb vendor would surpass godep and goppkg.in in one go.

**Comment by davecheney** [comment]
I'm not prepared to commit to that until Go packages have some notion of being released, otherwise we'll end up with the seven different kinds of tag soup that befell pythons various efforts.

**Comment by andrewchambers** [comment]
It does not necessarily mean a release. It just means a branch. It can be used for projects that depend on feature branches too.

It is a bit of a chicken and egg feature.

**Comment by andrewchambers** [comment]
I think one of the first features people will want is being able to specify a branch to gb vendor. Statically checking branches match across a project would stop some headaches for sure.

Anyway, I am really becoming happy with the direction of gb. Thanks for your hard work.
