### ISSUE TITLE
change -d to -R

### ISSUE THREAD

**Issue by tve** [constabulary/gb-vendor#8]
It looks to me like `gb` is using -R to specify the project root. Wouldn/'t it thus be nice for `gb-vendor` to use the same flag instead of `-d`?

**Comment by davecheney** [comment]
Thanks. I'll drop the -d flag altogether, gb vendor doesn't need it as it is always run as a plugin after detecting the project root.

**Comment by davecheney** [comment]
@tve it looks like `gb-vendor` also uses `-R`
```
        flag.StringVar(&projectdir, "R", os.Getenv("GB_PROJECT_DIR"), "project directory")
        flag.Parse()
```

**Comment by tve** [comment]
Ok, I must be looking at the wrong sources then. I'm seeing -p in https://github.com/constabulary/gb-vendor/blob/master/main.go#L16-L17, where should I be looking instead?

**Comment by davecheney** [comment]
You may be right, I may have not pushed my latest changes.

**Comment by davecheney** [comment]
I think I got it this time.
